### ISSUE TITLE
calismayan linkler.!

### ISSUE THREAD

**Issue by ahembal** [YEmreAk/YLib#17]
Onemli dizinlerin icindeki harici baglantilar calismiyor.

**Comment by yemreak** [comment]
Biraz daha ayrıntı verebilir misin?

> _Örneğin direkt olarak sayfanın linki olabilir_

**Comment by ahembal** [comment]
https://windows.yemreak.com/windowsa-giris/dizinler

bu sayfada harici baglantilar kismi..

**Comment by yemreak** [comment]
Düzeltildi ✔️
